# AI Camera Node Parameters for PiCarX
# Indent: 2 spaces
# ROS 2 YAML parameter file

picarx_rpiai_camera_node:
  ros__parameters:
    network_package: "/home/gzub/ros2-picarx/src/raspberrypi_ai_camera_ros2/networks/imx500_network_yolov8n_640x640_pp.rpk"
    labels_file: "/home/gzub/ros2-picarx/src/raspberrypi_ai_camera_ros2/labels/coco_yolo.txt"
    frame_id: "camera_frame"
    detection_threshold: 0.60
    iou_threshold: 0.70
    max_detections: 15
    ignore_dash_labels: false
    preserve_aspect_ratio: false
    inference_rate: 25
    output_directory: "image_out/"
    save_images: false
