controller_manager:
  ros__parameters:
    update_rate: 24
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    ackermann_steering_controller:
      type: ackermann_steering_controller/AckermannSteeringController

ackermann_steering_controller:
  ros__parameters:
    reference_timeout: 10.0
    steering_joints_names: ["left_steering_joint", "right_steering_joint"]
    traction_joints_names: ["left_rear_axle", "right_rear_axle"]
    wheelbase: 0.10         # Set to the distance between front and rear axles in meters (adjust as needed)
    traction_track_width: 0.115 # Set to the distance between left and right rear wheels in meters (adjust as needed)
    velocity_rolling_window_size: 10
    publish_rate: 24
    use_stamped_vel: true
    traction_wheels_radius: 0.0325 # Should match rear_wheel_diameter/2 from URDF
    open_loop: true
    enable_odom_tf: true
    base_frame_id: "base_link"

joint_state_broadcaster:
  ros__parameters:
    use_sim_time: false
