controller_manager:
  ros__parameters:
    update_rate: 24
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    ackermann_steering_controller:
      type: ackermann_steering_controller/AckermannSteeringController

ackermann_steering_controller:
  ros__parameters:
    base_frame_id: base_link
    enable_odom_tf: true
    max_speed: 0.2 # m/s
    max_steering_angle: 35.0 # degrees
    odom_frame_id: odom
    open_loop: true
    reference_timeout: 1.0
    steering_joints_names: ["left_steering_joint", "right_steering_joint"]
    steering_track_width: 0.115 # Set to the distance between left and right rear wheels in meters (adjust as needed)
    traction_joints_names: ["left_rear_axle", "right_rear_axle"]
    traction_track_width: 0.115 # Set to the distance between left and right rear wheels in meters (adjust as needed)
    traction_wheels_radius: 0.0325 # Should match rear_wheel_diameter/2 from URDF
    use_sim_time: false
    use_stamped_vel: true
    velocity_rolling_window_size: 10
    wheelbase: 0.10 # meters

joint_state_broadcaster:
  ros__parameters:
    use_sim_time: false
